length_name_maximum: 50
length_email_maximum: 255
length_password_minimum: 6
_true: "1"
host_heroku: "https://ancient-falls-61196.herokuapp.com"
host: "http://localhost:3000"
address: "smtp.gmail.com"
port: "587"
authentication: :plain,
domain: "gmail.com"
host_local: "localhost"
port_local: 3000
one: 1
three: 3
paginate_view_home: 8
limit_product: 8
size_image: "270x320"
size_image_cart: "50x50"
size_text_area: "5x10"
minimum: 1
history_order: 5
admin_user: 5
categories_admin: 5
min_price: 0
category:
  length_minimum: 5
description:
  length_minimum: 25
admin:
  product_limit: 5
